FROM node:12.13.1-alpine3.10
MAINTAINER support@tastytech.ca
LABEL tastytech.dentrino-web.base.version="1.0.2"

# Dependencies Pre-downloading
ARG BUILD_DIR=/build
WORKDIR $BUILD_DIR

ADD package.json ./package.json
ADD package-lock.json ./package-lock.json

RUN npm install
